### ISSUE TITLE
Discord to IRC: Long messages are cutting

### ISSUE THREAD

**Issue by Tridale** [GinjaNinja32/DisGoIRC#10]
Messages that are longer than the IRC character limits cut. Completely losing part of the message. This seems to be the issue mostly in the staff channel, or with long posts that are a large single paragraph instead of being broken up.

An example:
(01:44:56) DiscordBridge: <S﻿napshot> @Community Moderators please be careful that you don't accidentally kick any discord bots. It looks like someone with kick permissions did so and as a result we didn't have the bridge working for a good little while. They're a bit annoying to get back added onto the server. If you do accidentally kick it, just let myself or apples know so we can get it back on server quickly. While obviously having it be kicked is bad, it's 

That's all of the message that got to IRC.

**Comment by GinjaNinja32** [comment]
Doesn't appear to still be an issue.
